### ISSUE TITLE
Minified version Copy&Paste breaks tabSize 0

### ISSUE THREAD

**Issue by MarcosBL** [wjbryant/taboverride#9]
Found this problem while trying to use the tabSize(0) for normal tabs. The minified version lacks a couple "\t" strings, making it use 3 spaces if you copy&paste inside another file when size = 0. It works fine for any other length.

Culptrits seems to be (at least) this two parts:

```javascript
var l,m,n,o=window.document,p="	",q=9,r=9,s=[],t=["shiftKey"]
```
and
```javascript
for(p="",b=0;a>b;b+=1)p+=" ";else p="	";return this}return"	"===p?0:p.length
```

Those two should be, to allow for safe Copy&Paste:

```javascript
var l,m,n,o=window.document,p="\t",q=9,r=9,s=[],t=["shiftKey"]
```
and
```javascript
for(p="",b=0;a>b;b+=1)p+=" ";else p="\t";return this}return"\t"===p?0:p.length
```

Of course I know copying and pasting is not the way modern JS development works, but anyway is a small change in the minify process and it can help.

**Comment by wjbryant** [comment]
Thanks for reporting this. I've updated the build process to replace literal tab characters with \t in the minified output.
